services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-task-manager
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    container_name: db-task-manager
    restart: always
    ports:
      - "${DB_PORT-3306}:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD-secret}" 
        MYSQL_DATABASE: "${DB_DATABASE-task_manager}"
        MYSQL_USER: "${DB_USERNAME-laravel}"
        MYSQL_PASSWORD: "${DB_PASSWORD-secret}"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  dbdata:
    driver: local
